on: [push, workflow_dispatch]

jobs:
  duckgiri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: edave64/Doki-Doki-Dialog-Generator
          ref: master
          path: main
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        run: |
          cd main
          npm install
          npm run lint
          npm run assetConversions
          npm run build:web
      # I use bot creds so this
      - uses: Dobby233Liu/github-pages-deploy-action@dev-no-crap
        with:
          branch: gh-pages
          folder: dist
